UCSC/Controllers/CarrerasController.cs
using UCSC.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UCSC.Controllers
{
    public class CarrerasController : Controller
    {
        private gestion_eppEntities1 db = new gestion_eppEntities1();
        // GET: Carreras
        public ActionResult Index()
        {
            var carrera = db.Carrera.ToList();
            return View(carrera);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Carrera carrera)
        {
            db.Carrera.Add(carrera);
            db.SaveChanges();
            return View();
        }

        public ActionResult Edit(int? id)
        {
            Carrera carrera = db.Carrera.Find(id);
            return PartialView("_Edit", carrera);
        }
        [HttpPost]
        public ActionResult Edit(Carrera carrera)
        {
            db.Entry(carrera).State = EntityState.Modified;
            db.SaveChanges();
            return Json("");
        }

        public ActionResult Delete(int? id)
        {
            if (id != null)
            {
                var carrera = db.Carrera.Find(id);
                return PartialView("_Delete", carrera);
            }
            return View();
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var carrera = db.Carrera.Find(id);
            try
            {
                db.Carrera.Remove(carrera);
                db.SaveChanges();
                return Json("");
            }

            catch (Exception)
            {
                return Json("No se puede eliminar un Estado que ya se este utilizando.");
            }
        }




    }
}

UCSC/Controllers/CategoriasController.cs
using UCSC.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UCSC.Controllers
{
    public class CategoriasController : Controller
    {
        private gestion_eppEntities1 db = new gestion_eppEntities1();
        // GET: Categorias
        public ActionResult Index()
        {
            var categorias = db.Categoria.ToList();
            return View(categorias);
                     
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Categoria categoria)
        {
            db.Categoria.Add(categoria);
            db.SaveChanges();
            return View();
        }

        public ActionResult Edit(int? id)
        {
            Categoria categoria = db.Categoria.Find(id);
            return PartialView("_Edit", categoria);
        }
        [HttpPost]
        public ActionResult Edit(Categoria categoria)
        {
            db.Entry(categoria).State = EntityState.Modified;
            db.SaveChanges();
            return Json("");
        }
        public ActionResult Delete(int? id)
        {
            if (id != null)
            {
                var categoria = db.Categoria.Find(id);
                return PartialView("_Delete", categoria);
            }
            return View();
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var categoria = db.Categoria.Find(id);
            try
            {
                db.Categoria.Remove(categoria);
                db.SaveChanges();
                return Json("");
            }
            catch(Exception)
            {
                return Json("No se puede eliminar una categoria asignada.");
            }
           
           
        }


    }
}

UCSC/Controllers/EPPController.cs
using UCSC.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UCSC.Controllers
{
    public class EPPController : Controller
    {
        private gestion_eppEntities1 db = new gestion_eppEntities1();


        // GET: EPP
        public ActionResult Index()
        {

            var EPP = db.EPP.ToList();
            return View(EPP);
        }


        public ActionResult Create()
        {
            ViewBag.categoria = new SelectList(db.Categoria, "id_categoria", "nombre");
            //ViewBag.usuario = new SelectList(db.Usuario, "id_usuario", "nombre");

            return View();
        }

        [HttpPost]
        public ActionResult Create(EPP epp)
        {
            try
            {
                db.EPP.Add(epp);
                db.SaveChanges();
                return Json("");
            }

            catch (Exception)
            {
                return Json("Ha ocurrido un error, intentelo mas tarde.");
            }
        }

        public ActionResult Edit(int? id)
        {
           
            var epp = db.EPP.Find(id);
            
            ViewBag.Usuario = new SelectList(db.Usuario, "id_usuario", "nombre", epp.id_usuario);
            ViewBag.Categoria = new SelectList(db.Categoria, "id_categoria", "nombre", epp.id_categoria);
            ViewBag.estado = new SelectList(db.Estado, "id_estado", "nombre", epp.id_estado);
            return PartialView("_Edit", epp);
        }
        [HttpPost]
        public ActionResult Edit(EPP epp)
        {

            db.Entry(epp).State = EntityState.Modified;
            db.SaveChanges();
            return Json("");
        }


        public ActionResult Delete(int id)
        {
            var epp = db.EPP.Find(id);
            return PartialView("_Delete", epp);
        }
        [HttpPost]
        public ActionResult Eliminar(int id)
        {
            var epp = db.EPP.Find(id);
            if (epp != null)
            {
                db.EPP.Remove(epp);
                db.SaveChanges();
                return Json("");
            }
            return Json("No se ha podido eliminar el producto");
        }


    }
}

UCSC/Controllers/EstadoController.cs
using UCSC.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UCSC.Controllers
{
    public class EstadoController : Controller
    {
        private gestion_eppEntities1 db = new gestion_eppEntities1();
        // GET: Estado
        public ActionResult Index()
        {

            var estado = db.Estado.ToList();
            return View(estado);
            
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Estado estado)
        {
            db.Estado.Add(estado);
            db.SaveChanges();
            return View();
        }

        public ActionResult Edit(int? id)
        {
            Estado estado = db.Estado.Find(id);
            return PartialView("_Edit", estado);
        }
        [HttpPost]
        public ActionResult Edit(Estado estado)
        {
            db.Entry(estado).State = EntityState.Modified;
            db.SaveChanges();
            return Json("");
        }

        public ActionResult Delete(int? id)
        {
            if (id != null)
            {
                var estado = db.Estado.Find(id);
                return PartialView("_Delete", estado);
            }
            return View();
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var estado = db.Estado.Find(id);
            try
            {
                db.Estado.Remove(estado);
                db.SaveChanges();
                return Json("");
            }

            catch (Exception)
            {
                return Json("No se puede eliminar un Estado que ya se este utilizando.");
            }
        }



    }
}

UCSC/Views/Shared/_Layout.cshtml
@if (Session["tipoUsuario"] != null)
{
    <!DOCTYPE html>


<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="refresh" content="1800;url=../Usuario/Logout" />
    <title>@ViewBag.Title</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/animate.css" rel="stylesheet" />
    <link href="~/Content/style.css" rel="stylesheet" />
    <link href="~/fonts/font-awesome/css/font-awesome.min.css" rel="stylesheet" />

    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="~/Scripts/plugins/slimscroll/jquery.slimscroll.min.js"></script>
    <script src="~/Scripts/app/inspinia.js"></script>
    <script src="~/Scripts/plugins/pace/pace.min.js"></script>

</head>
<body>
    <div id="wrapper">
        <!--MENU-->
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav metismenu" id="side-menu">
                    <li class="nav-header">
                        <div class="profile-element">
                            <a href="#">

                                <span class="block m-t-xs font-bold">@Session["usuario"]</span>
                                <span class="text-muted text-xs block">@Session["tipoUsuario"]</span>
                            </a>
                        </div>
                        <div class="logo-element">
                            SI
                        </div>
                    </li>

                    


                    <!--Agregar links al menú -->
                    @if (Session["tipoUsuario"] != null)
                    {

                        if (Session["tipoUsuario"].Equals("Administrador"))
                        {
                            @Html.Partial("_MenuAdmin")
                        }
                        if (Session["tipoUsuario"].Equals("Encargado"))
                        {
                            @Html.Partial("_MenuEncargado")
                        }
                        if (Session["tipoUsuario"].Equals("Usuario"))
                        {
                            @Html.Partial("_MenuUsuario")
                        }
                    }
                    else
                    {
                        Response.Redirect("~/Usuarios/Login");
                    }



                </ul>
            </div>
        </nav>
        <!--FIN MENU-->

        <div id="page-wrapper" class="gray-bg">
            <!--TOP NAVBAR-->
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header">
                        <center>
                            <img src="https://i.ibb.co/HnMSrgQ/descarga.jpg" class="img-fluid" alt="Responsive image">
                        </center>

                    </div>
                    <ul class="nav navbar-top-links navbar-right">
                        <li style="padding:20px">
                            <h3><strong>Sistema de Gestión y Seguimiento de EPP </strong></h3>
                        </li>
                        <li>
                            <a href="@Url.Action("Logout", "Usuarios")">
                                <i class="fa fa-sign-out"></i> Desconectarse
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div>
                @*<a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>*@
            </div>
            <!--FIN TOP NAVBAR-->
            @RenderBody()
        </div>
    </div>
</body>



</html>
}
else
{
    Response.Redirect("~/Usuarios/Login");
}

UCSC/Views/Shared/_MenuAdmin.cshtml
<li>
    <a href="#"><i class="fa fa-amazon"></i><span class="nav-label">Categorías</span><span class="fa arrow"></span></a>
    <ul class="nav nav-second-level collapse">
        <li><a href="@Url.Action("Create", "Categorias")">Crear Categoría</a></li>
        <li><a href="@Url.Action("Index", "Categorias")">Lista Categorías</a></li>
    </ul>
</li>
<li>
    <a href="#"><i class="fa fa-ambulance"></i><span class="nav-label"> EPP </span><span class="fa arrow"></span></a>
    <ul class="nav nav-second-level collapse">
        <li><a href="@Url.Action("Create", "EPP")">Crear EPP</a></li>
        <li><a href="@Url.Action("Index","EPP")">Lista EPP</a></li>
    </ul>
</li>
<li>
    <a href="#"><i class="fa fa-address-book"></i><span class="nav-label">Usuario</span><span class="fa arrow"></span></a>
    <ul class="nav nav-second-level collapse">
        <li><a href="@Url.Action("Create", "Usuarios")">Crear Usuario</a></li>
        <li><a href="@Url.Action("Index","Usuarios")">Listar Usuarios</a></li>
    </ul>
</li>
<li>
    <a href="#"><i class="fa fa-users"></i><span class="nav-label">Tipos de Usuario</span><span class="fa arrow"></span></a>
    <ul class="nav nav-second-level collapse">
        <li><a href="@Url.Action("Create", "TipoUsuario")">Crear Tipo de Usuario</a></li>
        <li><a href="@Url.Action("Index","TipoUsuario")">Listar Tipos de Usuarios</a></li>
    </ul>
</li>
<li>
    <a href="#"><i class="fa fa-etsy"></i><span class="nav-label">Estados</span><span class="fa arrow"></span></a>
    <ul class="nav nav-second-level collapse">
        <li><a href="@Url.Action("Create", "Estado")">Crear Estado</a></li>
        <li><a href="@Url.Action("Index","Estado")">Listar Estados</a></li>
    </ul>
</li>
<li>
    <a href="#"><i class="fa fa-heartbeat"></i><span class="nav-label">Carreras</span><span class="fa arrow"></span></a>
    <ul class="nav nav-second-level collapse">
        <li><a href="@Url.Action("Create", "Carreras")">Crear Carrera</a></li>
        <li><a href="@Url.Action("Index","Carreras")">Listar Carreras</a></li>
    </ul>
</li>
<li>
    <a href="#"><i class="fa fa-sign-in"></i><span class="nav-label">Ingreso de Stock</span><span class="fa arrow"></span></a>
    <ul class="nav nav-second-level collapse">
        <li><a href="@Url.Action("OrdenEntrada", "OrdenEntradas")">Ingresar Stock</a></li>
        <li><a href="@Url.Action("Index", "OrdenEntradas")">Listar Stock</a></li>
    </ul>
</li>
<li>
    <a href="#"><i class="fa fa-sort-amount-asc"></i><span class="nav-label">Solicitud de EPP</span><span class="fa arrow"></span></a>
    <ul class="nav nav-second-level collapse">
        <li><a href="@Url.Action("OrdenSalida", "OrdenSalidas")">Petición de EPP</a></li>
        <li><a href="@Url.Action("ListadoSalidas", "OrdenSalidas")">Listar Pedidos</a></li>
    </ul>
</li>

UCSC/Views/Shared/_MenuEncargado.cshtml
<li>
    <a href="#"><i class="fa fa-amazon"></i><span class="nav-label">Categorías</span><span class="fa arrow"></span></a>
    <ul class="nav nav-second-level collapse">
        <li><a href="@Url.Action("Create", "Categorias")">Crear Categoría</a></li>
        <li><a href="@Url.Action("Index", "Categorias")">Lista Categorías</a></li>
    </ul>
</li>
<li>
    <a href="#"><i class="fa fa-ambulance"></i><span class="nav-label"> EPP </span><span class="fa arrow"></span></a>
    <ul class="nav nav-second-level collapse">
        <li><a href="@Url.Action("Create", "EPP")">Crear EPP</a></li>
        <li><a href="@Url.Action("Index","EPP")">Lista EPP</a></li>
    </ul>
</li>


<li>
    <a href="#"><i class="fa fa-etsy"></i><span class="nav-label">Estados</span><span class="fa arrow"></span></a>
    <ul class="nav nav-second-level collapse">
        <li><a href="@Url.Action("Create", "Estado")">Crear Estado</a></li>
        <li><a href="@Url.Action("Index","Estado")">Listar Estados</a></li>
    </ul>
</li>

<li>
    <a href="#"><i class="fa fa-sign-in"></i><span class="nav-label">Ingreso de Stock</span><span class="fa arrow"></span></a>
    <ul class="nav nav-second-level collapse">
        <li><a href="@Url.Action("OrdenEntrada", "OrdenEntradas")">Ingresar Stock</a></li>
        <li><a href="@Url.Action("Index", "OrdenEntradas")">Listar Stock</a></li>
    </ul>
</li>
<li>
    <a href="#"><i class="fa fa-sort-amount-asc"></i><span class="nav-label">Solicitud de EPP</span><span class="fa arrow"></span></a>
    <ul class="nav nav-second-level collapse">
        <li><a href="@Url.Action("OrdenSalida", "OrdenSalidas")">Petición de EPP</a></li>
        <li><a href="@Url.Action("ListadoSalidas", "OrdenSalidas")">Listar Pedidos</a></li>
    </ul>
</li>

UCSC/Views/Shared/_MenuUsuario.cshtml
<li>
    <a href="#"><i class="fa fa-sort-amount-asc"></i><span class="nav-label">Solicitud de EPP</span><span class="fa arrow"></span></a>
    <ul class="nav nav-second-level collapse">
        <li><a href="@Url.Action("OrdenSalida", "OrdenSalidas")">Petición de EPP</a></li>
        <li><a href="@Url.Action("ListadoSalidas", "OrdenSalidas")">Listar Pedidos</a></li>
    </ul>
</li>