UCSC/Models/OrdenSalida.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCSC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenSalida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenSalida()
        {
            this.DetalleSalida = new HashSet<DetalleSalida>();
        }
    
        public int id_orden { get; set; }
        public System.DateTime fecha_orden { get; set; }
        public Nullable<int> user_entrega { get; set; }
        public int user_pide { get; set; }
        public string ubicacion { get; set; }
        public int id_carrera { get; set; }
        public string periodo_uso { get; set; }
        public Nullable<int> cant_alumnos { get; set; }
        public System.DateTime fecha_requerida { get; set; }
        public Nullable<int> cant_docentes { get; set; }
        public string comentario { get; set; }
        public int id_estado { get; set; }
    
        public virtual Carrera Carrera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleSalida> DetalleSalida { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}

UCSC/Controllers/OrdenSalidaController.cs
using UCSC.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UCSC.Controllers
{
    public class OrdenSalidaController : Controller
    {
        private gestion_eppEntities1 db = new gestion_eppEntities1();
        // GET: OrdenSalida
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult OrdenSalida()
        {
            ViewBag.epp = new SelectList(db.EPP, "id_epp", "nombre");
            ViewBag.carrera = new SelectList(db.Carrera, "id_carrera", "nombre_carrera");
            return View();
        }

        [HttpPost]
        public JsonResult OrdenSalida(OrdenSalida orden, List<DetalleSalida> detalles)
        {
            orden.fecha_orden = DateTime.Now;
            orden.user_pide = 1015;
            orden.user_entrega = 1015;
            orden.id_estado = 5;
                        
            db.OrdenSalida.Add(orden);
            db.SaveChanges();


            var idDet = orden.id_orden;
            foreach (var item in detalles)
            {

                item.id_orden = idDet;
                db.DetalleSalida.Add(item);

                ActualizaStock(item.id_epp, item.cantidad);
                db.SaveChanges();
            }

            return Json("");
        }

        public void ActualizaStock(int id_epp, int cantidad)
        {

            var epp = db.EPP.Find(id_epp);

            epp.cantidad = epp.cantidad - cantidad;
            db.Entry(epp).State = EntityState.Modified;
        }

        public ActionResult ListadoSalidas()
        {
            var ordenes = db.OrdenSalida.ToList();
            return View(ordenes);
        }

        public ActionResult DetalleOrdenSalida(int id)
        {
            var detalle = db.OrdenSalida.Find(id);
            return View(detalle);
        }






    }
}

UCSC/Controllers/OrdenSalidasController.cs
using UCSC.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UCSC.Controllers
{
    public class OrdenSalidasController : Controller
    {
        private gestion_eppEntities1 db = new gestion_eppEntities1();
        // GET: OrdenSalida
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult OrdenSalida()
        {
            ViewBag.epp = new SelectList(db.EPP, "id_epp", "nombre");
            ViewBag.carrera = new SelectList(db.Carrera, "id_carrera", "nombre_carrera");
            return View();
        }

        [HttpPost]
        public JsonResult OrdenSalida(OrdenSalida orden, List<DetalleSalida> detalles)
        {
            orden.fecha_orden = DateTime.Now;
            orden.user_entrega = 1015;
            orden.id_estado = 5;
            bool actualizado = false;
                        
            db.OrdenSalida.Add(orden);
            db.SaveChanges();


            var idDet = orden.id_orden;
            foreach (var item in detalles)
            {

                item.id_orden = idDet;
                db.DetalleSalida.Add(item);
                
                actualizado = ActualizaStock((int)item.id_epp, item.cantidad);

                if (actualizado)
                {
                    db.SaveChanges();
                }
                else
                {
                    db.OrdenSalida.Remove(orden);
                    db.SaveChanges();
                    return Json("no");
                }
                
            }

            return Json("");
        }

        public bool ActualizaStock(int id_epp, int cantidad)
        {
            bool actualizadoCorrectamente = false;
            var epp = db.EPP.Find(id_epp);

            if (epp.cantidad > cantidad)
            {
                epp.cantidad = epp.cantidad - cantidad;
                db.Entry(epp).State = EntityState.Modified;
                actualizadoCorrectamente = true;
            }

            return actualizadoCorrectamente;
        }

        public ActionResult ListadoSalidas()
        {
            var ordenes = db.OrdenSalida.ToList();
            return View(ordenes);
        }

        public ActionResult DetalleOrdenSalida(int id)
        {
            var detalle = db.OrdenSalida.Find(id);
            return View(detalle);
        }

            
        public ActionResult Saberestado() //index 
        {
            return View();
        }

        public ActionResult Parchalbiu(int? id)
        {
            var ordencita = db.OrdenSalida.Find(id);
            return PartialView("_PopupEstadoConsulta", ordencita);
        }

        [HttpPost]
        public ActionResult Saberestado(int estadoreal)
        {
            var estado = db.OrdenSalida.FirstOrDefault(u => u.id_orden.Equals(estadoreal));
    
            return View("Parchalbiu", estado);
        }
                
        public ActionResult Delete(int id)
        {
            var ordensalida = db.OrdenSalida.Find(id);
            return PartialView("_Delete", ordensalida);
        }

        public ActionResult Eliminar(int id)
        {
            try
            {
                var ordenSal = db.OrdenSalida.OrderBy(o => o.id_orden).Include(o => o.DetalleSalida).First();
                db.OrdenSalida.Remove(ordenSal);
                db.SaveChanges();
                return Json("");
            }
            catch (Exception ex)
            {
                return Json("No se puede eliminar esta orden");
                throw;
            }
        }

        public ActionResult EditarOrden(int? id)
        {
            var ordensalida = db.OrdenSalida.Find(id);
            ViewBag.carrera = new SelectList(db.Carrera, "id_carrera", "nombre_carrera", ordensalida.id_carrera);
            ViewBag.estado = new SelectList(db.Estado, "id_estado", "nombre", ordensalida.id_estado);

            return PartialView("_EditarOrden", ordensalida);
        }

        [HttpPost]
        public ActionResult EditarOrden(OrdenSalida ordensalida)
        {
            try
            {
                db.Entry(ordensalida).State = EntityState.Modified;
                db.SaveChanges();
                return Json("");
            }
            catch (Exception)
            {
                return Json("No se ha podido editar");
                throw;
            }
        }

        public ActionResult EditarDetallesSalida (int? id)
        {
            var detallesalida = db.DetalleSalida.Find(id);
            ViewBag.epp = new SelectList(db.EPP, "id_epp", "nombre", detallesalida.id_epp);
            return PartialView("_EditarDetallesSalida", detallesalida);
        }

        [HttpPost]
        public ActionResult EditarDetallesSalida (DetalleSalida detallesalida)
        {
            try
            {
                db.Entry(detallesalida).State = EntityState.Modified;
                db.SaveChanges();
                return Json("");
            }
            catch (Exception ex)
            {
                return Json("No se ha podido editar");
                throw;
            }


        }


    }
}

UCSC/Views/OrdenSalidas/DetalleOrdenSalida.cshtml
@model UCSC.Models.OrdenSalida
@{
    ViewBag.Title = "DetalleOrdenSalida";
}

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox-title">
                <div class="form-group row">
                    <label class="col-2 text-right">N° Orden: </label>
                    <div class="col-sm-2">
                        <label>@Model.id_orden</label>
                    </div>
                    <label class="col-2 text-right">Usuario Ingreso: </label>
                    <div class="col-sm-2">
                        <label>@Model.Usuario.email</label>
                    </div>
                    <label class="col-2 text-right">Fecha Ingreso: </label>
                    <div class="col-sm-2">
                        <label>@Model.fecha_orden.ToShortDateString()</label>
                    </div>
                </div>
            </div>
            <div class="ibox-content">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead class="bg-primary">
                            <tr>
                                <th>Código Producto</th>
                                <th>Nombre</th>
                                <th>Cantidad</th>
                                <th>Editar</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.DetalleSalida)
                            {
                                <tr>
                                    <td>@item.EPP.id_epp</td>
                                    <td>@item.EPP.nombre</td>
                                    <td>@item.cantidad</td>
                                    <td>
                                        <button class="btn btn-warning" data-toggle="modal"
                                                data-url="@Url.Action("EditarDetallesSalida","OrdenSalidas",new { id = item.id_detalle })">
                                            <i class="fa fa-edit"></i>
                                        </button>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="~/Scripts/plugins/moment.min.js"></script>


<script src="~/Scripts/jquery.dataTables.min.js"></script>
<script src="~/Scripts/dataTables.bootstrap4.min.js"></script>




<script>
    $(document).ready(function () {
        $('#tabla').DataTable();
    });
</script>

<div class="modal fade" id="modalEdit"></div>

<script>
    $('.btn-warning').click(function () {
        let url = $(this).data('url');
        $.get(url, function (data) {
            $('#modalEdit').html(data);
            $('#modalEdit').modal('show');
        });
    });


</script>

UCSC/Views/OrdenSalidas/EstadoConsulta.cshtml
@{
    Layout = null;
}
@model IEnumerable<UCSC.Models.OrdenSalida>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Consulta estado</title>
    <link href="~/Content/BootstrapLogin.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/animate.css" rel="stylesheet" />
    <link href="~/Content/style.css" rel="stylesheet" />
    <link href="~/fonts/font-awesome/css/font-awesome.min.css" rel="stylesheet" />

    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="~/Scripts/plugins/slimscroll/jquery.slimscroll.min.js"></script>
    <script src="~/Scripts/app/inspinia.js"></script>
    <script src="~/Scripts/plugins/pace/pace.min.js"></script>


</head>
<body>
    <div>

        <!------ Include the above in your HEAD tag ---------->

        <div class="wrapper fadeInDown">
            <div id="formContent">
                <!-- Tabs Titles -->
                <!-- Icon -->

                <div class="fadeIn first">
                    <img src="https://i.ibb.co/HnMSrgQ/descarga.jpg" id="icon" alt="User Icon" />
                </div>

                <!-- Login Form -->
                
                    <h4><span class="label label-default">Ingrese numero de Pedido: </span></h4>
                    <input type="text" id="id_pedido" class="fadeIn second" name="id_pedido" placeholder="Por ejemplo: 1111">

                    <div>
                        <input type="submit" class="btn btn-warning" data-toggle="modal" id="botonestado">
                        
                        


                        @*<input type="submit" value="Consultar" />*@
                        @*<button class="btn btn-primary" data-toggle="modal">

            <i class="fa fa-edit"></i> Consultar
        </button>*@
                    </div>
                   


              

                <!-- Remind Passowrd -->


            </div>
        </div>

    </div>
</body>
</html>




<div class="modal fade" id="modalEdit"></div>

<script>
    

    $('#id_pedido').click(function () {
        let url = '/OrdenSalidas/PopupEstadoConsulta';
        let data = $('#id_pedido').val();
        $.get(url, function (data) {
            $('#modalEdit').html(data);
            $('#modalEdit').modal('show');
        });
    });

</script>

UCSC/Views/OrdenSalidas/ListadoSalidas.cshtml
@model IEnumerable<UCSC.Models.OrdenSalida>
@{
    ViewBag.Title = "ListadoSalidas";
}

<div>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap5.min.css">
    <h2>Historial Ordenes de Salidas</h2>

</div>
<hr />




<div class="dataTables_wrapper dt-bootstrap4">
    <table id="tabla" class="table table-striped table-bordered" style="width:100%">

        <thead>
            <tr>
                <th>Número Orden</th>
                <th>Fecha Ingreso</th>
                <th>Usuario Solicitante</th>
                <th>Usuario Entrega </th>
                <th>Campo Clinico </th>
                <th>Carrera </th>
                <th>Periodo duración</th>
                <th>Cantidad Alumnos</th>
                <th>Cantidad Docentes </th>
                <th>Fecha Requerida</th>
                <th>Comentario</th>
                <th>Estado</th>
                <th>Ver y editar detalles</th>
                <th>Editar Orden</th>
                <th>Eliminar</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {

                int idUsuario = int.Parse(Session["idusuario"].ToString());

                if (int.Parse(Session["idTipoUsuario"].ToString()) == 2009 && item.user_pide == idUsuario)
                {
                    <tr>
                        <td>@item.id_orden</td>
                        <td>@item.fecha_orden.ToShortDateString()</td>
                        @*<td>@item.Usuario.nombre</td>*@
                        <td>@item.Usuario1.email</td>
                        @*<td>@item.Usuario.nombre</td>*@
                        <td>@item.Usuario.email</td>
                        <td>@item.ubicacion</td>
                        <td>@item.Carrera.nombre_carrera</td>
                        <td>@item.periodo_uso</td>
                        <td>@item.cant_alumnos</td>
                        <td>@item.cant_docentes</td>
                        <td>@item.fecha_requerida.ToShortDateString()</td>
                        <td>@item.comentario</td>
                        <td>@item.Estado.nombre</td>
                        <td style="white-space: nowrap">
                            <a href="@Url.Action("DetalleOrdenSalida","OrdenSalidas",new { id = item.id_orden })" target="_blank" class="btn btn-warning">
                                <i class="fa fa-list"></i>
                            </a>
                        </td>
                        <td>
                            <button class="btn btn-warning" data-toggle="modal"
                                    data-url="@Url.Action("EditarOrden","OrdenSalidas",new { id = item.id_orden })">
                                <i class="fa fa-edit"></i>
                            </button>
                        </td>
                        <td>
                            <button class="btn btn-danger" data-toggle="modal"
                                    data-url="@Url.Action("Delete","OrdenSalidas", new { id = item.id_orden })">
                                <i class="fa fa-trash"></i>
                            </button>
                        </td>
                    </tr>
                }

                if (int.Parse(Session["idTipoUsuario"].ToString()) == 1006 || int.Parse(Session["idTipoUsuario"].ToString()) == 1007)

                {
                    <tr>
                        <td>@item.id_orden</td>
                        <td>@item.fecha_orden.ToShortDateString()</td>
                        <td>@item.Usuario.email</td>
                        <td>@item.Usuario1.email</td>
                        <td>@item.ubicacion</td>
                        <td>@item.Carrera.nombre_carrera</td>
                        <td>@item.periodo_uso</td>
                        <td>@item.cant_alumnos</td>
                        <td>@item.cant_docentes</td>
                        <td>@item.fecha_requerida.ToShortDateString()</td>
                        <td>@item.comentario</td>
                        <td>@item.Estado.nombre</td>
                        <td style="white-space: nowrap">
                            <a href="@Url.Action("DetalleOrdenSalida","OrdenSalidas",new { id = item.id_orden })" target="_blank" class="btn btn-warning">
                                <i class="fa fa-list"></i>
                            </a>
                        </td>
                        <td>
                            <button class="btn btn-warning" data-toggle="modal"
                                    data-url="@Url.Action("EditarOrden","OrdenSalidas",new { id = item.id_orden })">
                                <i class="fa fa-edit"></i>
                            </button>
                        </td>
                        <td>
                            <button class="btn btn-danger" data-toggle="modal"
                                    data-url="@Url.Action("Delete","OrdenSalidas", new { id = item.id_orden })">
                                <i class="fa fa-trash"></i>
                            </button>
                        </td>
                    </tr>
                }
            }

        </tbody>
    </table>
    <button id="botonexcel" class="btn btn-success">Exportar a Excel</button>
    <button id="botonpdf" class="btn btn-secondary">Exportar a PDF</button>
</div>



<script src="~/Scripts/plugins/moment.min.js"></script>


<script src="~/Scripts/jquery.dataTables.min.js"></script>
<script src="~/Scripts/dataTables.bootstrap4.min.js"></script>

<script src="~/Scripts/jquery.table2excel.js"></script>
<script src="~/Scripts/tableHTMLExport.js"></script>
<script src="~/Scripts/jspdf.min.js"></script>
<script src="~/Scripts/jspdf.plugin.autotable.min.js"></script>



<script>
    $(document).ready(function () {
        $('#tabla').DataTable();
    });
</script>

<div class="modal fade" id="modalEdit"></div>
<div class="modal fade" id="modalDelete"></div>
<script>
    $('.btn-warning').click(function () {
        let url = $(this).data('url');
        $.get(url, function (data) {
            $('#modalEdit').html(data);
            $('#modalEdit').modal('show');
        });
    });
    $('.btn-danger').click(function () {
        let url = $(this).data('url');
        $.get(url, function (data) {
            $('#modalDelete').html(data);
            $('#modalDelete').modal('show');
        });
    });

    $("#botonexcel").click(function () {

        $("#tabla").table2excel({

            // exclude CSS class

            exclude: ".noExl",

            name: "Worksheet Name",

            filename: "SomeFile",//do not include extension

            fileext: ".xls" // file extension

        });

    });

    $("#botonpdf").click(function () {
        $("#tabla").tableHTMLExport({

            // csv, txt, json, pdf
            type: 'pdf'
          

        });
    });
    

</script>

UCSC/Views/OrdenSalidas/OrdenSalida.cshtml
@{
    ViewBag.Title = "OrdenEntrada";
}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <script src="~/Scripts/plugins/gijgo.min.js" type="text/javascript"></script>

    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />

</head>

<div class="row wrapper border-bottom white-bg page-heading">

    <h2>Solicitud de EPP</h2>
</div>




@if (Session["tipoUsuario"] != null)
{

    if (Session["tipoUsuario"].Equals("Administrador"))
    {
        @Html.Partial("_PeticionAdmin")
    }
    if (Session["tipoUsuario"].Equals("Encargado"))
    {
        @Html.Partial("_PeticionAdmin")
    }
    if (Session["tipoUsuario"].Equals("Usuario"))
    {
        @Html.Partial("_PeticionUser")
    }
}
else
{
    Response.Redirect("~/Usuarios/Login");
}


<div class="modal fade" id="modalEdit"></div>

<script>
    $('.btn-warning').click(function () {
        let url = $(this).data('url');
        $.get(url, function (data) {
            $('#modalEdit').html(data);
            $('#modalEdit').modal('show');
        });
    });


</script>

UCSC/Views/OrdenSalidas/Parchalbiu.cshtml
@model UCSC.Models.OrdenSalida

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Estado Pedido de EPP</title>
    <link href="~/Content/BootstrapLogin.css" rel="stylesheet" id="bootstrap-css">

    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>


</head>
<body>
    <div>

        <!------ Include the above in your HEAD tag ---------->

        <div class="wrapper fadeInDown">
            <div id="formContent">
                <!-- Tabs Titles -->
                <!-- Icon -->

                <div class="fadeIn first">
                    <img src="https://i.ibb.co/HnMSrgQ/descarga.jpg" id="icon" alt="User Icon" />
                </div>

                <!-- Login Form -->
                <form>
                    <input type="text" placeholder=" @Model.Estado.nombre" disabled>

                    
                    
                </form>
                <div>
                    <h6><span class="label label-info">Para cualquier consulta sobre el estado de su Pedido de EPP, puede comunicarse al correo: asistente.medicina@ucsc.cl</span></h6>
                </div>


             

            </div>
        </div>

    </div>
</body>
</html>

<script>

    $(document).ready(function () {

        let varimagen = @Model.Estado.nombre
        alert(varimagen)

    });

   

</script>

UCSC/Views/OrdenSalidas/Saberestado.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Consulta Estado de Solicitud</title>
    <link href="~/Content/BootstrapLogin.css" rel="stylesheet" id="bootstrap-css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>



</head>
<body>
    <div>

        <div class="wrapper fadeInDown">
            <div id="formContent">
   
                <div class="fadeIn first">
                    <img src="https://i.ibb.co/HnMSrgQ/descarga.jpg" id="icon" alt="User Icon" />
                </div>
                <!-- Login Form -->
                <form action="@Url.Action("Saberestado")" method="post">
                    <input type="text" id="login" class="fadeIn second" name="estadoreal" placeholder="Ingresa numero de Orden">
                    <input type="submit" class="fadeIn fourth" value="Buscar">
                </form>

            </div>
        </div>

    </div>
</body>
</html>

<div class="modal fade" id="modalEdit"></div>

<script>
    $(document).ready(function () {
        $('#submit').on('click', function (e) {
            e.preventDefault();
            $('#modalEdit').modal('show');
        });

    });

</script>

UCSC/Views/OrdenSalidas/_Delete.cshtml
@model UCSC.Models.OrdenSalida

<div class="modal-dialog">
    <div class="modal-content">
        <!-- Modal Header -->
        <div class="modal-header">
            <h4 class="modal-title">Eliminar Usuario</h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <!-- Modal body -->
        <div class="modal-body">
            <input type="hidden" id="id" value="@Model.id_orden" />
            <h2>¿Desea eliminar el pedido : N°<b>@Model.id_orden</b> ?</h2>
        </div>

        <!-- Modal footer -->
        <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
            <input type="button" id="eliminar" value="Eliminar" class="btn btn-primary" />
        </div>
    </div>
</div>

<script src="~/Scripts/plugins/sweetalert/sweetalert.min.js"></script>
<script>
    $('#eliminar').click(function () {


        $.ajax({
            type: 'POST',
            url: '@Url.Action("Eliminar")',
            data: '{id:' + JSON.stringify($('#id').val()) + '}',
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            success: function (resp) {
                if (resp == '') {
                    swal({
                        title: 'Eliminar Orden',
                        text: 'Se ha eliminado con éxito el registro',
                        icon: 'success',
                        button: 'Cerrar',
                        closeOnClickOutside: false,
                    }).then(function (isConfirm) {
                        if (isConfirm) {
                            location.reload();
                        }
                    });

                } else {
                    swal("Eliminar", resp, "error");
                }
            }
        });
    });
</script>

UCSC/Views/OrdenSalidas/_EditarDetallesSalida.cshtml
@model UCSC.Models.DetalleSalida

<div class="modal-dialog">
    <div class="modal-content">
        <!-- Modal Header -->
        <div class="modal-header">
            <h4 class="modal-title">Editar Detalle Pedido EPP</h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <!-- Modal body -->
        <div class="modal-body">
            <input type="hidden" id="id_detalle" value="@Model.id_detalle" />
            <input type="hidden" id="id_orden" value="@Model.id_orden" />



            <div class="form-group row">
                <label class="col-2 text-right">Producto:</label>
                <div class="col-10">
                    @Html.DropDownList("epp", null, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group row">
                <label class="col-2 text-right">Cantidad:</label>
                <div class="col-10">
                    <input type="number" name="cantidad" id="cantidad" min="0" value="@Model.cantidad" class="form-control solonumeros" />
                </div>
            </div>

        </div>

        <!-- Modal footer -->
        <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
            <input type="button" value="Editar" class="btn btn-primary" id="editar" />
        </div>
    </div>
</div>
<script src="~/Scripts/plugins/sweetalert/sweetalert.min.js"></script>

<script>
    $('#editar').click(function () {
        let error = '';

        if ($('#cantidad').val() === '')
            error += 'Debe ingresar cantidad \n';


        if (error != '') {
            swal('Error validación', error, 'error');
        }
        else
        {
            const epp = {
                id_detalle: $('#id_detalle').val(),
                id_epp: $('#epp').val(),
                cantidad: $('#cantidad').val(),
                id_orden: $('#id_orden').val()


            }

            $.ajax({
                type: 'POST',
                url: '@Url.Action("EditarDetallesSalida")',
                data: '{detallesalida:' + JSON.stringify(epp) + '}',
                dataType: 'json',
                contentType: 'application/json; charset=utf-8',
                success: function (resp) {
                    if (resp == "") {
                        $('#modalEdit').modal('hide');
                        swal({
                            title: 'Modificar Detalle',
                            text: 'Los datos se han guardado con éxito!',
                            icon: 'success',
                            button: 'Cerrar',

                            closeOnClickOutside: false,
                        }).then(function (isConfirm) {
                            if (isConfirm) {
                                location.reload();
                            }
                        });
                    }
                }
            });
        }
    });


</script>