UCSC/Models/OrdenEntrada.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCSC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenEntrada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenEntrada()
        {
            this.DetalleEntrada = new HashSet<DetalleEntrada>();
        }
    
        public int id_orden { get; set; }
        public System.DateTime fecha { get; set; }
        public int id_usuario { get; set; }
        public string comentario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleEntrada> DetalleEntrada { get; set; }
    }
}

UCSC/Controllers/OrdenEntradasController.cs
using UCSC.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UCSC.Controllers
{
    public class OrdenEntradasController : Controller
    {
        private gestion_eppEntities1 db = new gestion_eppEntities1();
        // GET: OrdenEntradas
        public ActionResult OrdenEntrada()
        {
            ViewBag.epp = new SelectList(db.EPP, "id_epp", "nombre");
            return View();
        }

        [HttpPost]
        public JsonResult OrdenEntrada(OrdenEntrada orden, List<DetalleEntrada> detalles)
        {
            
            orden.fecha = DateTime.Now;
            orden.id_usuario = 1015;
            db.OrdenEntrada.Add(orden);
            db.SaveChanges();
            
            var idDet = orden.id_orden;
            
            foreach (var item in detalles)
            {
               
                item.id_orden = idDet;
                db.DetalleEntrada.Add(item);
                
                ActualizaStock(item.id_epp, item.cantidad);
                db.SaveChanges();
            }
            return Json("");
        }
        public void ActualizaStock(int id_epp, int cantidad)
        {
           
            var epp = db.EPP.Find(id_epp);
            
            epp.cantidad = epp.cantidad + cantidad;
            db.Entry(epp).State = EntityState.Modified;
        }


        [HttpPost]
        public ActionResult EPPExiste(string nombre)
        {
            var q = db.EPP.FirstOrDefault(p => p.nombre.ToLower().Equals(nombre.ToLower()));
            if(q != null)
            {
                return Json(new { q.nombre, q.id_epp },JsonRequestBehavior.AllowGet);
            }
            return Json("");
        }

        public ActionResult Index ()
        {
            var ordenes = db.OrdenEntrada.ToList();
            return View(ordenes);
        }

       
        public ActionResult DetalleOrden(int id)
        {
            //Obtiene el id orden
            var detalle = db.OrdenEntrada.Find(id);

           
            return View(detalle);
        }

        
        public ActionResult Delete(int id)
        {
            var ordenentrada = db.OrdenEntrada.Find(id);
            return PartialView("_Delete", ordenentrada);
        }
        [HttpPost]
        public ActionResult Eliminar(int id)
        {
            try
            {
                var ordenEnt = db.OrdenEntrada.OrderBy(o => o.id_orden).Include(o => o.DetalleEntrada).First();

                db.OrdenEntrada.Remove(ordenEnt);

                db.SaveChanges();
                return Json("");
            }
            catch (Exception)
            {
                return Json("No se puede eliminar esta orden");
                throw;
            }
            

        }

          
        public ActionResult Edit(int? id)
        {
            ViewBag.epp = new SelectList(db.EPP, "id_epp", "nombre");
            //var detalleEntrada = db.DetalleEntrada.Where(d => d.id_detalle == id);
            var detalleEntrada = db.DetalleEntrada.Find(id);


            return PartialView("_Edit", detalleEntrada);
        }
        [HttpPost]
        public ActionResult Edit(DetalleEntrada detalleEntrada)
        {

            db.Entry(detalleEntrada).State = EntityState.Modified;
            db.SaveChanges();
            return Json("");
        }

        public ActionResult EditarDetalles (int? id)
        {
            var detalleentrada = db.DetalleEntrada.Find(id);
            ViewBag.epp = new SelectList(db.EPP, "id_epp", "nombre", detalleentrada.id_epp);
            return PartialView("_EditarDetalles", detalleentrada);
        }

        [HttpPost]
        public ActionResult EditarDetalles(DetalleEntrada detalleentrada)
        {
            try
            {
                db.Entry(detalleentrada).State = EntityState.Modified;
                db.SaveChanges();
                return Json("");
            }
            catch (Exception ex)
            {
                return Json("No se ha podido editar");
                throw;
            }
            
            
        }


    }
}

UCSC/Views/OrdenEntradas/DetalleOrden.cshtml
@model UCSC.Models.OrdenEntrada
@{
    ViewBag.Title = "DetalleOrden";
}
@if (Session["tipoUsuario"].Equals("Usuario"))
{
    Response.Redirect("~/OrdenSalidas/OrdenSalida");
}

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox-title">
                <div class="form-group row">
                    <label class="col-2 text-right">N° Orden: </label>
                    <div class="col-sm-2">
                        <label>@Model.id_orden</label>
                    </div>
                    <label class="col-2 text-right">Usuario Ingreso: </label>
                    <div class="col-sm-2">
                        <label>@Model.Usuario.email</label>
                    </div>
                    <label class="col-2 text-right">Fecha Ingreso: </label>
                    <div class="col-sm-2">
                        <label>@Model.fecha.ToShortDateString()</label>
                    </div>
                </div>
            </div>
            <div class="ibox-content">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead class="bg-primary">
                            <tr>
                                <th style="width:100px">Código Producto</th>
                                <th>Nombre</th>
                                <th>Cantidad</th>
                                <th>Editar</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.DetalleEntrada)
                            {
                                <tr>
                                    <td>@item.EPP.id_epp</td>
                                    <td>@item.EPP.nombre</td>
                                    <td>@item.cantidad</td>
                                    <td>
                                        <button class="btn btn-warning" data-toggle="modal"
                                                data-url="@Url.Action("EditarDetalles","OrdenEntradas",new { id = item.id_detalle })">
                                            <i class="fa fa-edit"></i>
                                        </button>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="~/Scripts/plugins/moment.min.js"></script>


<script src="~/Scripts/jquery.dataTables.min.js"></script>
<script src="~/Scripts/dataTables.bootstrap4.min.js"></script>




<script>
    $(document).ready(function () {
        $('#tabla').DataTable();
    });
</script>

<div class="modal fade" id="modalEdit"></div>

<script>
    $('.btn-warning').click(function () {
        let url = $(this).data('url');
        $.get(url, function (data) {
            $('#modalEdit').html(data);
            $('#modalEdit').modal('show');
        });
    });


</script>

UCSC/Views/OrdenEntradas/Index.cshtml
@model IEnumerable<UCSC.Models.OrdenEntrada>
@{
    ViewBag.Title = "Index";
}
@if (Session["tipoUsuario"].Equals("Usuario"))
{
    Response.Redirect("~/OrdenSalidas/OrdenSalida");
}
<div>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap5.min.css">
    <h2>Historial Ordenes de entradas</h2>

</div>
<hr />
<div class="dataTables_wrapper dt-bootstrap4">
    <table id="tabla" class="table table-striped table-bordered" style="width:100%">

        <thead>
            <tr>
                <th class="">Número Orden</th>
                <th>Fecha Ingreso</th>
                <th>Usuario Ingreso</th>
                <th>Comentario</th>
                <th>Ver detalles</th>
                @*<th>Editar</th>*@
                <th>Eliminar</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td width="100">@item.id_orden</td>
                    <td width="150">@item.fecha.ToShortDateString()</td>
                    <td>@item.Usuario.email</td>
                    <td>@item.comentario</td>
                    <td style="white-space: nowrap">
                        <a href="@Url.Action("DetalleOrden","OrdenEntradas",new { id = item.id_orden })" target="_blank" class="btn btn-success">
                            <i class="fa fa-list"></i>
                        </a>
                    </td>
                    @*<td>
                            <button class="btn btn-warning" data-toggle="modal"
                                    data-url="@Url.Action("Edit","OrdenEntradas",new { id = item.id_orden })">
                                <i class="fa fa-edit"></i>
                            </button>
                        </td>*@
                    <td>
                        <button class="btn btn-danger" data-toggle="modal"
                                data-url="@Url.Action("Delete","OrdenEntradas", new { id = item.id_orden })">
                            <i class="fa fa-trash"></i>
                        </button>
                    </td>
                </tr>
            }




        </tbody>
    </table>
</div>

<div>

</div>





<script src="~/Scripts/plugins/moment.min.js"></script>


<script src="~/Scripts/jquery.dataTables.min.js"></script>
<script src="~/Scripts/dataTables.bootstrap4.min.js"></script>




<script>
    $(document).ready(function () {
        $('#tabla').DataTable();
    });
</script>

<div class="modal fade" id="modalEdit"></div>
<div class="modal fade" id="modalDelete"></div>
<script>
    $('.btn-warning').click(function () {
        let url = $(this).data('url');
        $.get(url, function (data) {
            $('#modalEdit').html(data);
            $('#modalEdit').modal('show');
        });
    });
    $('.btn-danger').click(function () {
        let url = $(this).data('url');
        $.get(url, function (data) {
            $('#modalDelete').html(data);
            $('#modalDelete').modal('show');
        });
    });

</script>

UCSC/Views/OrdenEntradas/OrdenEntrada.cshtml
@{
    ViewBag.Title = "OrdenEntrada";
}
@if (Session["tipoUsuario"].Equals("Usuario"))
{
    Response.Redirect("~/OrdenSalidas/OrdenSalida");
}
<div class="row wrapper border-bottom white-bg page-heading">
    <h2>Entrada de Stock</h2>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox-title">
                <h3>Ingrese los datos de la entrada de Stock</h3>
            </div>
            <div class="ibox-content">

                <div class="form-group row">
                    <label class="col-sm-1">Nombre: </label>
                    <div class="col-sm-4">
                        @Html.DropDownList("epp", null, "Seleccione epp", htmlAttributes: new { @class = "form-control select2" })

                    </div>
                    <label class="col-sm-1">Cantidad: </label>
                    <div class="col-sm-2">
                        <input type="number" min="0" name="cantidad" class="form-control" id="cantidad" />
                    </div>
                    <input type="button" id="agregar" value="Agregar" class="btn btn-primary" />
                </div>
                <div>
                    <hr>
                </div>
                <div id="tablaEPP" class="form-group row">
                    <hr />
                    <div class="table-responsive">
                        <table id="detalleEPP" class="table">
                            <thead>
                                <tr>
                                    <th width="100">Código</th>
                                    <th>Nombre</th>
                                    <th>Cantidad</th>
                                </tr>
                            </thead>
                            <tbody> </tbody>
                        </table>



                    </div>



                </div>
                <div>
                    <hr>
                    <div class="form-group row">
                        <label class="col-sm-1">Comentario</label>
                        <div class="col-sm-7">
                            <input type="text" id="comentario" class="form-control" />
                        </div>
                    </div>
                    <div>
                        <input type="button" id="guardar" value="Guardar" class="btn btn-success" />
                    </div>
                </div>


            </div>
        </div>
    </div>
</div>

<link href="~/Content/plugins/sweetalert/sweetalert.css" rel="stylesheet" />
<link href="~/Content/plugins/select2/select2.min.css" rel="stylesheet" />
<script src="~/Scripts/plugins/sweetalert/sweetalert.min.js"></script>
<script src="~/Scripts/plugins/select2/select2.full.min.js"></script>
<script src="~/Scripts/plugins/sweetalert/sweetalert.min.js"></script>

<script>





    //select2
    let datos = [];
    let id_epp = 0;
    let nombre = '';

    $('.select2').select2();

    $('#agregar').click(function () {

        let error = '';
        if ($('#epp').val().trim() == '')
            error = 'Debe ingresar un producto \n';
        console.log(error);
        if ($('#cantidad').val() <= 0)
            error += 'Debe ingresar cantidad de EPP';
        if (error != '')
            swal('Error', error, 'warning');
        else {
            let modelo = {
                id_epp: $('#epp').val().trim(),
                nombre: $('#epp option:selected').text(),
                cantidad: $('#cantidad').val()
            };

            let x = 0;

            if (datos.length > 0) {

                for (let i = 0; i < datos.length; i++) {
                    if (datos[i].id_epp == modelo.id_epp) {
                        datos[i].cantidad = modelo.cantidad;
                        x = 1;
                        break;
                    }
                }
                if (x == 0) {
                    datos.push(modelo);
                }
            }
            else {
                datos.push(modelo);
            }

            cargarTablaDetalle();
            limpiar();
        }
        function cargarTablaDetalle() {
            $('#detalleEPP tbody').empty()
            for (let i = 0; i < datos.length; i++) {
                fila = '<tr>';
                fila += '<td>' + datos[i].id_epp + '</td>';
                fila += '<td>' + datos[i].nombre + '</td>';
                fila += '<td>' + datos[i].cantidad + '</td>';
                fila += "<td><button class='btn btn-danger eliminar'><span class='fa fa-trash'></span></button>";
                fila += '</tr>';
                $('#detalleEPP tbody').append(fila);
                eliminar();
            }
        }

        function eliminar() {
            $('.eliminar').click(function () {

                //obtener el código de la fila donde se presiona el botón de trash
                let cod = $(this).parents('tr').find('td').eq(0).html();
                for (let i = 0; i < datos.length; i++) {
                    if (datos[i].id_epp == cod) {
                        datos.splice(i, 1);//splice sirve para sacar elementos del arreglo
                    }
                }
                //llamar a función cargar tabla para recargar el arreglo en la tabla
                cargarTablaDetalle();
                //si la cantidad de elementos que hay en la tabla es == 0 la oculta

            });
        }

        function limpiar() {
            $('#cantidad').val('');
            $('#epp').val('');
            $('#epp').select2("val", "");
            }

    });

    $('#guardar').click(function () {
        //validación de datos
        let error = '';

        if (datos.length == 0)
            error += 'Debe agregar productos';
        if (error != '')
            swal('Error', error, 'warning');
        else {
            const ordenEntrada = {
                comentario: $('#comentario').val()
            }
            $.ajax({
                type: 'POST',
                url: '@Url.Action("OrdenEntrada")',
                data: '{orden:' + JSON.stringify(ordenEntrada) + ',detalles:' + JSON.stringify(datos) + '}',
                dataType: 'json',
                contentType: 'application/json;charset=utf-8',
                success: function (resp) {
                    if (resp == '') {
                        swal({
                            title: 'Ingreso',
                            text: 'Los datos se han guardado con éxito!',
                            icon: 'success',
                            button: 'Cerrar',
                            closeOnClickOutside: false,
                        }).then(function (isConfirm) {
                            if (isConfirm) {
                                location.reload();//recarga la página
                            }
                        });
                    }
                }

            });
        }
    });







</script>

UCSC/Views/OrdenEntradas/_Delete.cshtml
@model UCSC.Models.OrdenEntrada

<div class="modal-dialog">
    <div class="modal-content">
        <!-- Modal Header -->
        <div class="modal-header">
            <h4 class="modal-title">Eliminar Usuario</h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <!-- Modal body -->
        <div class="modal-body">
            <input type="hidden" id="id" value="@Model.id_orden" />
            <h2>¿Desea eliminar el producto: <b>@Model.id_orden</b> ?</h2>
        </div>

        <!-- Modal footer -->
        <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
            <input type="button" id="eliminar" value="Eliminar" class="btn btn-primary" />
        </div>
    </div>
</div>

<script src="~/Scripts/plugins/sweetalert/sweetalert.min.js"></script>
<script>
    $('#eliminar').click(function () {


        $.ajax({
            type: 'POST',
            url: '@Url.Action("Eliminar")',
            data: '{id:' + JSON.stringify($('#id').val()) + '}',
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            success: function (resp) {
                if (resp == '') {
                    swal({
                        title: 'Eliminar Orden',
                        text: 'Se ha eliminado con éxito el registro',
                        icon: 'success',
                        button: 'Cerrar',
                        closeOnClickOutside: false,
                    }).then(function (isConfirm) {
                        if (isConfirm) {
                            location.reload();
                        }
                    });

                } else {
                    swal("Eliminar", resp, "error");
                }
            }
        });
    });
</script>

UCSC/Views/OrdenEntradas/_Edit.cshtml
@model UCSC.Models.DetalleEntrada

<div class="row wrapper border-bottom white-bg page-heading">
    <h2>Entrada de Stock</h2>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox-title">
                <h3>Ingrese los datos de la entrada de Stock</h3>
            </div>
            <div class="ibox-content">
                <input type="hidden" id="id_orden" value="@Model.id_orden" />
                
                <div class="form-group row">
                    <label class="col-sm-1">Nombre: </label>
                    <div class="col-sm-4">
                        @Html.DropDownList("epp", null, "Seleccione epp", htmlAttributes: new { @class = "form-control select2" })

                    </div>
                    <label class="col-sm-1">Cantidad: </label>
                    <div class="col-sm-2">
                        <input type="number" name="cantidad" class="form-control" id="cantidad" />
                    </div>
                    <input type="button" id="agregar" value="Agregar" class="btn btn-primary" />
                </div>
                <div>
                    <hr>
                </div>
                <div id="tablaEPP" class="form-group row">
                    <hr />
                    <div class="table-responsive">
                        <table id="detalleEPP" class="table">
                            <thead>
                                <tr>
                                    <th>Código</th>
                                    <th>Nombre</th>
                                    <th>Cantidad</th>
                                </tr>
                            </thead>
                            <tbody>
                                
                            </tbody>
                        </table>



                    </div>



                </div>
                <div>
                    <hr>
                    <div class="form-group row">
                        <label class="col-sm-1">Comentario</label>
                        <div class="col-sm-7">
                            <input type="text" id="comentario" class="form-control" />
                        </div>
                    </div>
                    <div>
                        <input type="button" id="guardar" value="Guardar" class="btn btn-success" />
                    </div>
                </div>


            </div>
        </div>
    </div>
</div>

<link href="~/Content/plugins/sweetalert/sweetalert.css" rel="stylesheet" />
<link href="~/Content/plugins/select2/select2.min.css" rel="stylesheet" />
<script src="~/Scripts/plugins/sweetalert/sweetalert.min.js"></script>
<script src="~/Scripts/plugins/select2/select2.full.min.js"></script>
<script src="~/Scripts/plugins/sweetalert/sweetalert.min.js"></script>

<script>
    //select2
    let datos = [];
    let id_epp = 0;
    let id_orden = 0;
    let nombre = '';
    let nombreParaEdita = "";
    let cantidadParaEdit = "";

    //pasar el modelo como variable de sesión
    //--------

    //Función recibe un arreglo de datos para utilizar
    function cargarTablaDetalle(datos) {

        $('#detalleEPP tbody').empty()
        for (let i = 0; i < datos.length; i++) {
            fila = '<tr>';
            //fila += '<td>' + datos[i].id_epp + '</td>';
            //fila += '<td>' + datos[i].nombre + '</td>';
            //fila += '<td>' + datos[i].cantidad + '</td>';
            fila += '<td>' + datos[i] + '</td>';
            fila += '<td>' + datos[i] + '</td>';
            fila += '<td>' + datos[i] + '</td>';
            fila += "<td><button class='btn btn-danger eliminar'><span class='fa fa-trash'></span></button>";
            fila += '</tr>';

            $('#detalleEPP tbody').append(fila);
            eliminar();
        }
    }



    //Función para cargar la tablA EN EL INIT
    $(document).ready(function ()
    {



        @*let modelo = {

            id_orden: @Model.id_orden,
            nombreParaEdita: @Model.EPP.nombre,
            cantidadParaEdit: parseInt(@Model.cantidad),
        };*@


        alert(@Model.id_orden);

        datos.push(modelo);
        cargarTablaDetalle(datos);
    });



    $('.select2').select2();


    $('#agregar').click(function () {

        let error = '';
        if ($('#epp').val().trim() == '')
            error = 'Debe ingresar un producto \n';
        console.log(error);
        if ($('#cantidad').val() <= 0)
            error += 'Debe ingresar cantidad de EPP';
        if (error != '')
            swal('Error', error, 'warning');
        else {
            let modelo = {
               
                id_epp: $('#epp').val().trim(),
                nombre: $('#epp option:selected').text(),
                cantidad: $('#cantidad').val()
            };

            let x = 0;

            if (datos.length > 0) {

                for (let i = 0; i < datos.length; i++) {
                    if (datos[i].id_epp == modelo.id_epp) {
                        datos[i].cantidad = modelo.cantidad;
                        x = 1;
                        break;
                    }
                }
                if (x == 0) {
                    datos.push(modelo);
                }
            }
            else {
                datos.push(modelo);
            }

            cargarTablaDetalle(datos);
            limpiar();
        }

        

    });

    $('#guardar').click(function () {
        //validación de datos
        let error = '';

        if (datos.length == 0)
            error += 'Debe agregar productos';
        if (error != '')
            swal('Error', error, 'warning');
        else {
            const ordenEntrada = {
                comentario: $('#comentario').val()
            }
            $.ajax({
                type: 'POST',
                url: '@Url.Action("OrdenEntrada")',
                data: '{orden:' + JSON.stringify(ordenEntrada) + ',detalles:' + JSON.stringify(datos) + '}',
                dataType: 'json',
                contentType: 'application/json;charset=utf-8',
                success: function (resp) {
                    if (resp == '') {
                        swal({
                            title: 'Ingreso',
                            text: 'Los datos se han guardado con éxito!',
                            icon: 'success',
                            button: 'Cerrar',
                            closeOnClickOutside: false,
                        }).then(function (isConfirm) {
                            if (isConfirm) {
                                location.reload();//recarga la página
                            }
                        });
                    }
                }

            });
        }
    });


    function eliminar() {
        $('.eliminar').click(function () {

            //obtener el código de la fila donde se presiona el botón de trash
            let cod = $(this).parents('tr').find('td').eq(0).html();
            for (let i = 0; i < datos.length; i++) {
                if (datos[i].id_epp == cod) {
                    datos.splice(i, 1);//splice sirve para sacar elementos del arreglo
                }
            }
            //llamar a función cargar tabla para recargar el arreglo en la tabla
            cargarTablaDetalle();
            //si la cantidad de elementos que hay en la tabla es == 0 la oculta

        });
    }

    function limpiar() {

        $('#cantidad').val('');
        $('#epp').val();
        $('#epp').select2("val", "");
    }




</script>

UCSC/Views/OrdenEntradas/_EditarDetalles.cshtml
@model UCSC.Models.DetalleEntrada


<div class="modal-dialog">
<div class="modal-content">
    <!-- Modal Header -->
    <div class="modal-header">
        <h4 class="modal-title">Detalle Detalle Pedido</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
    </div>
    <!-- Modal body -->
    <div class="modal-body">
        <input type="hidden" id="id_detalle" value="@Model.id_detalle" />
        <input type="hidden" id="id_orden" value="@Model.id_orden" />



        <div class="form-group row">
            <label class="col-2 text-right">Producto:</label>
            <div class="col-10">
                @Html.DropDownList("epp", null, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group row">
            <label class="col-2 text-right">Cantidad:</label>
            <div class="col-10">
                <input type="number" name="cantidad" id="cantidad" value="@Model.cantidad" class="form-control solonumeros" />
            </div>
        </div>

    </div>

    <!-- Modal footer -->
    <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
        <input type="button" value="Editar" class="btn btn-primary" id="editar" />
    </div>
</div>
</div>
<script src="~/Scripts/plugins/sweetalert/sweetalert.min.js"></script>

<script>
    $('#editar').click(function () {
        let error = '';

        if ($('#cantidad').val() === '')
            error += 'Debe ingresar cantidad \n';
       

        if (error != '') {
            swal('Error validación', error, 'error');
        }
        else
        {
            const epp = {
                id_detalle: $('#id_detalle').val(),
                id_epp: $('#epp').val(),
                cantidad: $('#cantidad').val(),
                id_orden: $('#id_orden').val()
                

            }

            $.ajax({
                type: 'POST',
                url: '@Url.Action("EditarDetalles")',
                data: '{detalleentrada:' + JSON.stringify(epp) + '}',
                dataType: 'json',
                contentType: 'application/json; charset=utf-8',
                success: function (resp) {
                    if (resp == "") {
                        $('#modalEdit').modal('hide');
                        swal({
                            title: 'Modificar Detalle',
                            text: 'Los datos se han guardado con éxito!',
                            icon: 'success',
                            button: 'Cerrar',

                            closeOnClickOutside: false,
                        }).then(function (isConfirm) {
                            if (isConfirm) {
                                location.reload();
                            }
                        });
                    }
                }
            });
        }
    });


</script>